language: cpp

# Downloading ccache's cache is around 6s, uploading is around 3s.
cache: ccache

# The following two lines are required to use Docker.
sudo: required
services:
    - docker

# What branches are we reacting upon.
branches:
    only:
    - master
    - pre-release
    - coverity_scan
    - /^20..Q.*/


env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "dkaHaPCuL2rUcUprWCDCkpJZIho9oX6Ns5GtC9I1HLjaRV7K2LuNFbHN1k+D/nQcA7etg9GSiVzFxhrJpch+0KyJnqX5VOj73wvshhplDfn1D2ap/Z5IH2NHQ6tZWL6gkEcXaHk82k5wyfNoh6qsxdy2jw1rJCzuHWX8Zojz2w0hqCYh1sTsWCA8gS6FQjtyU1f5i357ywXncK/LWsXXsxfErqI1caemI0VzAR5pQ3KFo8WDZ190yc1SWspsIM7I4NtSqxvuLJLEsEnLoy65yiEs0C2rJ+zXLe7WRyvxfJLJ5XbvAecvh57IqlcpN31owj34AJAoS6aHAYgW73YUqGRozfWLAY2pxwtpKlefCHh/kxNUjROIbe9aNLLgoz9y9Iwe7zoRwM3yvg54/4J3VPG00n5sCPbweE15QoQcmgJIGeocTUCV1JaG1Qx1wLZEWatcmMr/RWimxhDrU6QKpHNYym4LJJI3Z30qSTNrfm8i7LuiJ1bN0lSSYHAUNw2Bl33eU7dEFKbXLkP5ffECCZBRW1Z5mP1RwmGoX/PtFR7UZMAamLR51+/ATwLx0mnGyPi+ZVUKuQ4L062Ak8SM5cYRPFHZXD9l149Ez/9RMopZig9WnXayn3+VjgXTACY29SYjgZJVBgMzIhjEDn2JIogGJnsJ6sAYGISu+MBiGys="


matrix:
  include:
    # clang 5.0: Regular build using Travis' default compiler for performance reasons to determine the code coverage when running the test cases on any branch (except for coverity_scan) or PR.
    - os: linux
      if: branch != coverity_scan
      compiler: clang
      env:
        - DO_COVERAGE=1
        - DO_COVERITY_SCAN=0
        - DO_DOCKER_BUILD=0
        - COMPILER_CC=clang
        - COMPILER_CXX=clang++
        - PATH=/usr/local/clang-5.0.0/bin:$PATH
        - CXXFLAGS="-stdlib=libc++"
        - LD_LIBRARY_PATH=/usr/local/clang-5.0.0/lib:$LD_LIBRARY_PATH
        - BUILD=Debug

    # clang/OSX: Build for pre-release to check if OSX could be built.
    - os: osx
      osx_image: xcode9.1
      if: branch = pre-release
      compiler: clang
      env:
        - DO_COVERAGE=0
        - DO_COVERITY_SCAN=0
        - DO_DOCKER_BUILD=0
        - COMPILER_CC=clang
        - COMPILER_CXX=clang++
        - BUILD=Release

    # clang 4.0/armhf: Build for pre-release to check if armhf could be built.
    - os: linux
      if: branch = pre-release
      compiler: clang
      env:
        - DO_COVERAGE=0
        - DO_COVERITY_SCAN=0
        - DO_DOCKER_BUILD=1
        - COMPILER_CC=
        - COMPILER_CXX=
        - BUILD=
        - DOCKER_BUILD_ARCH=armhf

    # GCC 6: Regular build to run coverity_scan analysis.
    - os: linux
      if: branch = coverity_scan
      compiler: gcc
      env:
        - DO_COVERAGE=0
        - DO_COVERITY_SCAN=1
        - DO_DOCKER_BUILD=0
        - COMPILER_CC=gcc-6
        - COMPILER_CXX=g++-6
        - BUILD=Debug
        - COVERITY_SCAN_PROJECT_NAME="chrberger/libcluon"
        - COVERITY_SCAN_BRANCH_PATTERN="coverity_scan"
        - COVERITY_SCAN_NOTIFICATION_EMAIL="libcluon@christianberger.net"
        - COVERITY_SCAN_BUILD_COMMAND_PREPEND="mkdir -p builds/non-docker && cd builds/non-docker && cmake -D CMAKE_BUILD_TYPE=Release ../../libcluon"
        - COVERITY_SCAN_BUILD_COMMAND="make"
      addons:
        apt:
          sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages: # TODO: Check if the regular output from llvm-cov could work as well instead kcov.
            - gcc-6
            - g++-6


before_install:
    # Steps for coverity_scan.
    - if [[ ${DO_COVERITY_SCAN} == "1" ]]; then echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-; fi
    # Re-adjust compiler symlinks to make coverity_scan work properly.
    - if [[ ${DO_COVERITY_SCAN} == "1" ]]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90; fi
    - if [[ ${DO_COVERITY_SCAN} == "1" ]]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90; fi
    # The following call is actually executing the build.
    - if [[ ${DO_COVERITY_SCAN} == "1" ]]; then curl -s 'https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh' | bash || true; fi

    # Fixes for ccache and clang.
    - if [[ "${DO_DOCKER_BUILD}" == "0" ]]; then if [[ "${DO_COVERITY_SCAN}" == "0" ]]; then if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo ln -s /usr/bin/ccache /usr/lib/ccache/clang; fi; fi; fi
    - if [[ "${DO_DOCKER_BUILD}" == "0" ]]; then if [[ "${DO_COVERITY_SCAN}" == "0" ]]; then if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo ln -s /usr/bin/ccache /usr/lib/ccache/clang++; fi; fi; fi
    # This environment variable is needed to let ccache handle the preprocessor from clang correctly.
    - if [[ "${DO_DOCKER_BUILD}" == "0" ]]; then if [[ "${DO_COVERITY_SCAN}" == "0" ]]; then if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then export CCACHE_CPP2=yes; fi; fi; fi


install:
    - if [[ "${COMPILER_CC}" != "" ]]; then export CC=${COMPILER_CC}; fi
    - if [[ "${COMPILER_CXX}" != "" ]]; then export CXX=${COMPILER_CXX}; fi


# Enabling ARM emulation.
before_script:
    - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo sh -c "echo ':arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-arm-static:' > /proc/sys/fs/binfmt_misc/register"; fi


script:
    - if [[ "${DO_DOCKER_BUILD}" == "0" ]]; then if [[ "${DO_COVERAGE}" == "0" ]]; then if [[ "${DO_COVERITY_SCAN}" == "0" ]]; then mkdir -p builds/non-docker && cd builds/non-docker && cmake -D CMAKE_BUILD_TYPE=${BUILD} -D ENABLE_COVERAGE=${DO_COVERAGE} ../../libcluon && make && make test; fi; fi; fi
    - if [[ "${DO_DOCKER_BUILD}" == "0" ]]; then if [[ "${DO_COVERAGE}" == "1" ]]; then if [[ "${DO_COVERITY_SCAN}" == "0" ]]; then if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then mkdir -p builds/non-docker && cd builds/non-docker && cmake -D CMAKE_BUILD_TYPE=${BUILD} -D ENABLE_COVERAGE=${DO_COVERAGE} ../../libcluon && make && make test && for i in $(grep '^[^#[:space:]].*:' Makefile|grep "ShowCoverage_"|grep -v ".PHONY"|grep -v "/fast:"|cut -f1 -d":"); do make $i; done | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g" | sed -e '/\/catch.hpp/,/^$/d' | sed -e '/^\/usr\/include/,/^$/d' | sed -e '/\[100%\]/d' | sed -e 's/.*\libcluon\/src/libcluon\/src/g' | sed -e 's/.*\libcluon\/test/libcluon\/test/g' > app.coverage.txt; fi; fi; fi; fi
    - if [[ "${DO_DOCKER_BUILD}" == "0" ]]; then if [[ "${DO_COVERITY_SCAN}" == "1" ]]; then echo "coverity_scan build executed."; fi; fi
    - if [[ "${DO_DOCKER_BUILD}" == "1" ]]; then make ARCH=$DOCKER_BUILD_ARCH IMAGE=debian-$DOCKER_BUILD_ARCH; fi


after_success:
  - if [[ "${DO_COVERAGE}" == "1" ]]; then bash <(curl -s https://codecov.io/bash); fi


notifications:
  email:
    recipients:
      - libcluon@christianberger.net
    on_success: change
    on_failure: always

